# Generated by Django 4.2.5 on 2023-09-28 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemorder',
            options={'verbose_name': 'Item order', 'verbose_name_plural': 'items orders'},
        ),
    ]
